# Generated by Django 4.2.2 on 2023-07-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_prducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prducto',
            new_name='Producto',
        ),
    ]
