# Generated by Django 4.2.2 on 2023-07-28 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_lineapedidio_lineapedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
            preserve_default=False,
        ),
    ]
