# Generated by Django 4.2.2 on 2023-07-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidio',
            name='user',
        ),
        migrations.DeleteModel(
            name='LineaPedidio',
        ),
        migrations.DeleteModel(
            name='Pedidio',
        ),
    ]
